// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxyzyxnipsoiomfywcix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4eXp5eG5pcHNvaW9tZnl3Y2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTk5MzYsImV4cCI6MjA1ODQ5NTkzNn0.uotQQ3JRVBw8tq_XDwgKAcYB-Zp2hgfPNOOIz8ChSD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);